import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BookDown,
  Briefcase,
  Copy,
  FileDown,
  Github,
  GraduationCap,
  Home,
  Mail,
  Palette,
  PenLine,
  Rocket,
  ScanFace,
  ScrollText,
  TrendingUp,
  User,
  UtensilsCrossed,
  Volume2,
  VolumeX,
  Wrench,
} from "lucide-react";
import { nextAccent, type Accent } from "@/lib/store/experience";

/**
 * v3 — Command palette action registry.
 *
 * Pure data only (no React) so the palette component can stay focused on
 * rendering + execution. `buildPaletteActions` receives the live experience
 * state and returns the full, freshly-labelled action list every time the
 * store changes (sound/accent labels are dynamic).
 *
 * Every `id` doubles as the analytics action id fired to /api/track
 * ({ type: "palette", action }) after the action executes.
 */

/** Contact email copied by the palette action. */
export const PALETTE_EMAIL = "jj@onyx.studio";

/** PLACEHOLDER GitHub URL — same placeholder used across the site's socials. */
export const PALETTE_GITHUB_URL = "https://github.com/jjonyx";

/** Static PDFs served from /public. The portfolio deck is generated by a
 *  parallel task — the action ships regardless (404 only if the file is
 *  not there yet, by design). */
export const RESUME_PDF = {
  href: "/resume/joseph-james-resume.pdf",
  filename: "joseph-james-resume.pdf",
};
export const PORTFOLIO_PDF = {
  href: "/portfolio/joseph-james-portfolio.pdf",
  filename: "joseph-james-portfolio.pdf",
};

export type PaletteGroup = "navigate" | "cases" | "actions";

export interface PaletteActionDef {
  /** Analytics id — fired to /api/track as { type: "palette", action } on run. */
  id: string;
  group: PaletteGroup;
  label: string;
  icon: LucideIcon;
  /** Extra hidden search terms fed into cmdk's value. */
  keywords?: string;
  /** Internal route — presence marks this as a router navigation action. */
  route?: string;
  /** Static file download — presence marks this as a download action. */
  file?: { href: string; filename: string };
}

/** Live experience state the labels depend on. */
export interface PaletteContext {
  muted: boolean;
  accent: Accent;
  gemUnlocked: boolean;
}

export const PALETTE_GROUPS: readonly PaletteGroup[] = [
  "navigate",
  "cases",
  "actions",
];

export const GROUP_HEADING: Record<PaletteGroup, string> = {
  navigate: "Navigate",
  cases: "Case Studies",
  actions: "Actions",
};

export function buildPaletteActions(ctx: PaletteContext): PaletteActionDef[] {
  const next = nextAccent(ctx.accent, ctx.gemUnlocked);
  const accentLabel =
    next === "mint"
      ? "Switch to emerald accent"
      : next === "prism"
        ? "Switch to prism accent"
        : "Switch to gold accent";

  return [
    // ── NAVIGATE ────────────────────────────────────────────────────────
    { id: "nav:/", group: "navigate", label: "Home", icon: Home, route: "/", keywords: "landing start intro" },
    { id: "nav:/about", group: "navigate", label: "About", icon: User, route: "/about", keywords: "bio story duality" },
    { id: "nav:/work", group: "navigate", label: "Work", icon: Briefcase, route: "/work", keywords: "projects systems portfolio" },
    { id: "nav:/startup", group: "navigate", label: "Startup", icon: Rocket, route: "/startup", keywords: "venture mission building" },
    { id: "nav:/blog", group: "navigate", label: "Journal", icon: PenLine, route: "/blog", keywords: "blog writing posts articles" },
    { id: "nav:/contact", group: "navigate", label: "Contact", icon: Mail, route: "/contact", keywords: "email message hire talk" },
    { id: "nav:/uses", group: "navigate", label: "Uses", icon: Wrench, route: "/uses", keywords: "setup gear tools kit" },
    { id: "nav:/now", group: "navigate", label: "Now", icon: Activity, route: "/now", keywords: "current status activity update" },
    { id: "nav:/resume", group: "navigate", label: "Resume", icon: ScrollText, route: "/resume", keywords: "cv experience career" },

    // ── CASE STUDIES ────────────────────────────────────────────────────
    { id: "case:tgs-restaurant-erp", group: "cases", label: "TGS Restaurant ERP", icon: UtensilsCrossed, route: "/work/tgs-restaurant-erp", keywords: "pos kitchen socket orders restaurant" },
    { id: "case:attendx", group: "cases", label: "AttendX", icon: ScanFace, route: "/work/attendx", keywords: "attendance face recognition checkin" },
    { id: "case:jj-nexus-pro", group: "cases", label: "JJ Nexus Pro", icon: TrendingUp, route: "/work/jj-nexus-pro", keywords: "trading forex streaming rtmp broadcast" },
    { id: "case:learnyx-academy", group: "cases", label: "Learnyx Academy", icon: GraduationCap, route: "/work/learnyx-academy", keywords: "ai exam eheee tutor education" },

    // ── ACTIONS ─────────────────────────────────────────────────────────
    {
      id: "toggle-sound",
      group: "actions",
      label: ctx.muted ? "Sound off" : "Sound on",
      icon: ctx.muted ? VolumeX : Volume2,
      keywords: "mute unmute audio ambient volume music",
    },
    {
      id: "toggle-accent",
      group: "actions",
      label: accentLabel,
      icon: Palette,
      keywords: "theme color gold emerald mint prism",
    },
    {
      id: "copy-email",
      group: "actions",
      label: "Copy email",
      icon: Copy,
      keywords: `mail contact clipboard ${PALETTE_EMAIL}`,
    },
    {
      id: "open-github",
      group: "actions",
      label: "Open GitHub",
      icon: Github,
      keywords: "profile code repos social external",
    },
    {
      id: "download-resume",
      group: "actions",
      label: "Download resume PDF",
      icon: FileDown,
      file: RESUME_PDF,
      keywords: "cv download save",
    },
    {
      id: "download-portfolio",
      group: "actions",
      label: "Download portfolio deck",
      icon: BookDown,
      file: PORTFOLIO_PDF,
      keywords: "deck case studies download save",
    },
  ];
}
